"""
Step 5 - Native Dart Code Exporter
===================================
Trains a highly-interpretable Decision Tree on the extracted features.
Instead of exporting to Pickle or TFLite, it parses the sklearn tree structure
and automatically generates a wildly-fast, pure Dart class.
"""

import os
import json
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

# ── Config ─────────────────────────────────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FEATURES_FILE = os.path.join(BASE_DIR, 'data', 'features.csv')
DART_OUTPUT = os.path.join(BASE_DIR, '..', 'crash_detection_auth', 'lib', 'services', 'crash_model.dart')

if not os.path.exists(FEATURES_FILE):
    raise FileNotFoundError("Run 2_features.py first.")

# ── Load Data ──────────────────────────────────────────────────────────────
df = pd.read_csv(FEATURES_FILE)
X = df.drop(columns=['label', 'fall_type'])
y = df['label']
features_list = list(X.columns)

# Provide more weight to crashes to ensure high recall
sample_weights = np.where(y == 1, 5.0, 1.0)

# ── Train Model ────────────────────────────────────────────────────────────
print("Training highly-optimized Decision Tree...")
# Limiting depth to 6 keeps the Dart code extremely fast and prevents overfitting
model = DecisionTreeClassifier(max_depth=6, class_weight='balanced', random_state=42)
model.fit(X, y, sample_weight=sample_weights)

preds = model.predict(X)
f1 = f1_score(y, preds)
print(f"Training F1 Score: {f1:.4f}")

# ── Recursive Dart Exporter ────────────────────────────────────────────────
def export_tree_to_dart(tree_, feature_names):
    tree = tree_.tree_
    
    def recurse(node, depth):
        indent = "  " * depth
        if tree.feature[node] != -2: # Not a leaf
            name = feature_names[tree.feature[node]]
            threshold = tree.threshold[node]
            left_child = tree.children_left[node]
            right_child = tree.children_right[node]
            
            # Map Python feature names to Dart feature names (from FeatureExtractor)
            # Our feature extractor outputs a Map<String, dynamic>. 
            # E.g. features['gForce_max']
            code = f"{indent}if (f['{name}']! <= {threshold:.5f}) {{\n"
            code += recurse(left_child, depth + 1)
            code += f"{indent}}} else {{\n"
            code += recurse(right_child, depth + 1)
            code += f"{indent}}}\n"
            return code
        else: # Leaf
            value = tree.value[node][0]
            # Convert counts/weights at leaf to a probability
            prob_crash = value[1] / (value[0] + value[1])
            return f"{indent}return {prob_crash:.4f};\n"

    dart_body = recurse(0, 1)
    
    dart_class = f"""// AUTO-GENERATED ML MODEL
// Do not edit manually. Generated by ml_model/5_export_dart.py
// Training F1 Score: {f1:.4f}

class CrashModel {{
  /// Analyzes a 1-second rolling window of sensor features.
  /// Returns the probability (0.0 to 1.0) of a crash.
  static double predict(Map<String, dynamic> f) {{
{dart_body}
  }}
}}
"""
    return dart_class

# ── Save Dart File ─────────────────────────────────────────────────────────
print(f"\nGenerating native Dart model...")
dart_code = export_tree_to_dart(model, features_list)

os.makedirs(os.path.dirname(DART_OUTPUT), exist_ok=True)
with open(DART_OUTPUT, 'w') as f:
    f.write(dart_code)

print(f"✅ Exported to {DART_OUTPUT}")
print("   The model is now pure native Dart machine code!")
