// AUTO-GENERATED ML MODEL
// Do not edit manually. Generated by ml_model/5_export_dart.py
// Training F1 Score: 0.4528

class CrashModel {
  /// Analyzes a 1-second rolling window of sensor features.
  /// Returns the probability (0.0 to 1.0) of a crash.
  static double predict(Map<String, dynamic> f) {
  if (f['gForce_max']! <= 1.05616) {
    if (f['az_min']! <= 0.94900) {
      return 0.0000;
    } else {
      if (f['az_mean']! <= 9.89164) {
        if (f['az_range']! <= 0.19750) {
          return 0.0000;
        } else {
          if (f['rz_range']! <= 2.84350) {
            if (f['rotation_iqr']! <= 0.45432) {
              return 0.0000;
            } else {
              return 0.9901;
            }
          } else {
            if (f['rx_rms']! <= 3.13595) {
              return 0.0000;
            } else {
              return 0.0000;
            }
          }
        }
      } else {
        return 0.0000;
      }
    }
  } else {
    return 0.0000;
  }

  }
}
