import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';

import 'firebase_options.dart';
import 'providers/auth_provider.dart';
import 'providers/profile_provider.dart';
import 'providers/sensor_provider.dart';
import 'screens/emergency_contacts_screen.dart';
import 'screens/home_screen.dart';
import 'screens/login_screen.dart';
import 'screens/phone_otp_screen.dart';
import 'screens/profile_screen.dart';
import 'screens/sensor_dashboard_screen.dart';
import 'screens/emergency_countdown_screen.dart';
import 'screens/splash_screen.dart';
import 'services/backend_api_service.dart';
import 'services/firebase_auth_service.dart';
import 'services/profile_api_service.dart';
import 'services/secure_storage_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Lock to portrait-only (remove if landscape is needed).
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Translucent status bar.
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.light,
  ));

  // Initialise Firebase using the options generated by FlutterFire CLI.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const CrashDetectionApp());
}

class CrashDetectionApp extends StatelessWidget {
  const CrashDetectionApp({super.key});

  @override
  Widget build(BuildContext context) {
    // ── Service instances (singletons) ──────────────────────────────────────
    final firebaseAuthService = FirebaseAuthService();
    final secureStorageService = SecureStorageService();
    final backendApiService = BackendApiService(
      authService: firebaseAuthService,
      storageService: secureStorageService,
    );
    final profileApiService = ProfileApiService(
      backendApiService: backendApiService,
    );

    return MultiProvider(
      providers: [
        ChangeNotifierProvider<AppAuthProvider>(
          create: (_) => AppAuthProvider(
            authService: firebaseAuthService,
            storageService: secureStorageService,
            backendApiService: backendApiService,
          ),
        ),
        ChangeNotifierProvider<ProfileProvider>(
          create: (_) => ProfileProvider(
            profileApiService: profileApiService,
          ),
        ),
        ChangeNotifierProvider<SensorProvider>(
          create: (_) => SensorProvider(
            storageService: secureStorageService,
          ),
        ),
      ],
      child: MaterialApp(
        title: 'Crash Detection',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          useMaterial3: true,
          colorScheme: ColorScheme.fromSeed(
            seedColor: const Color(0xFF4FC3F7),
            brightness: Brightness.dark,
          ),
          textTheme: GoogleFonts.interTextTheme(
            ThemeData.dark().textTheme,
          ),
          scaffoldBackgroundColor: const Color(0xFF0F2027),
          snackBarTheme: SnackBarThemeData(
            backgroundColor: const Color(0xFF203A43),
            contentTextStyle:
                const TextStyle(color: Colors.white, fontSize: 14),
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12)),
          ),
        ),
        // ── Routes ───────────────────────────────────────────────────────────
        initialRoute: SplashScreen.routeName,
        routes: {
          SplashScreen.routeName: (_) => const SplashScreen(),
          LoginScreen.routeName: (_) => const LoginScreen(),
          PhoneOtpScreen.routeName: (_) => const PhoneOtpScreen(),
          HomeScreen.routeName: (_) => const HomeScreen(),
          ProfileScreen.routeName: (_) => const ProfileScreen(),
          EmergencyContactsScreen.routeName: (_) =>
              const EmergencyContactsScreen(),
          SensorDashboardScreen.routeName: (_) =>
              const SensorDashboardScreen(),
          EmergencyCountdownScreen.routeName: (_) =>
              const EmergencyCountdownScreen(),
        },
      ),
    );
  }
}
